### ISSUE TITLE
Implement Direction Fix

### ISSUE THREAD

**Issue by MetalES** [MetalES/Project-Zelda#13]
See http://forum.solarus-games.org/index.php/topic,584.0.html

Works great
https://www.youtube.com/watch?v=CVyGcq-jNy8&feature=youtu.be

- [x] Bow
    - [x]  Clean code (Total lengh before : 11088; Total lengh after : 9602)
    - [x]  Replace hero state collision check 

- [x] Hookshot
    - [x]  Clean code (Total lengh before : 22988; Total lengh after : 18662)
    - [x]  Replace hero state collision check 

- [x] Boomerang
    - [x]  Clean code (Total lengh before : 20809; Total lengh after : 16264)
    - [x]  Replace hero state collision check 

- [ ] Dominion Rod
    - [ ]  Clean code (Total lengh before :  n/a)
    - [ ]  Replace hero state collision check 

- [x] Delete their tunic sprite id and merge them in the tunic default animation

- [x] Delete any collision check that imply checking hero position on the map, it is now not necessary (and it saves a lot performance-wise)

+ Check if hero:unfreeze is necessary when encountering something like a stair or water since animation can be canceled instead of restoring a tunic sprite id

Oh wow it actually works, i'm surprised

**Comment by Diarandor** [comment]
There may a small issue in the following situation that you should check:

If you push a wall when sidewalking with a weapon, maybe the pushing animation is started (I solved this for the custom sword and was even able to code the "tapping" action). This can be fixed by adding a few more lines of code to the script, to fix the pushing animation while the weapon is being used to sidewalk. 

Don't hesitate to ask me in case you need some help, since these things are annoying and take much time.

**Comment by MetalES** [comment]
This is the last thing I need to do and items will be completed.

The problem is, canceling an item because of pushing a wall is kinda lame, I'm gonna look at this
